<p>Ejemplo Numpy</p>

In [1]:
import pandas as pd
import numpy as np
from numpy import linalg #Algebra lineal

In [2]:
v = np.array([1,2,3])

In [3]:
print(v)

[1 2 3]


In [4]:
m = np.array([[1,2,3],[0,1,4],[5,6,0]])
print(m)

[[1 2 3]
 [0 1 4]
 [5 6 0]]


In [5]:
print(m[0,0])

1


In [6]:
print(m[2,1])

6


In [7]:
print(v @ m) #Multiplicacion de vector y matriz

[16 22 11]


In [8]:
m_inv = linalg.inv(m) #Inversa de la matriz m

In [9]:
print(m_inv)

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [10]:
print(m @ m_inv) #Multiplicacion de m por su inversa

[[ 1.00000000e+00 -1.77635684e-15 -4.44089210e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [2]:
df = pd.read_csv('Titanic/titanic.csv')

<h3>Visualizar y extraer informacion</h3>

In [3]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

In [4]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
df.shape

(891, 12)

In [6]:
df.iloc[5] #Fila en la posicion 5, 6ta fila

PassengerId                   6
Survived                      0
Pclass                        3
Name           Moran, Mr. James
Sex                        male
Age                         NaN
SibSp                         0
Parch                         0
Ticket                   330877
Fare                     8.4583
Cabin                       NaN
Embarked                      Q
Name: 5, dtype: object

In [7]:
df.iloc[:2] #Filas en el rango[0,2), la fila en posicion 2 no es incluida

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [8]:
df.iloc[0,0] #Celda en la posicion 0,0

1

In [9]:
df.iloc[[0,10,12],3:6] #Filas 0,10,10, y las columnas [3,6). La columna en la poicion 6 no se incluye

Name     Sex   Age
0           Braund, Mr. Owen Harris    male  22.0
10  Sandstrom, Miss. Marguerite Rut  female   4.0
12   Saundercock, Mr. William Henry    male  20.0

Con .loc nos referimos a los indices

In [10]:
df.loc[0] #fila con indice 0

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                                 22
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [11]:
df.loc[0, 'Fare'] #fila con indice 0 y columnba Fare

7.25

In [12]:
df.loc[:3, 'Sex': 'Fare'] #Filas con indices en el rango de [0:3] y columnas entre sex y fare

Sex   Age  SibSp  Parch            Ticket     Fare
0    male  22.0      1      0         A/5 21171   7.2500
1  female  38.0      1      0          PC 17599  71.2833
2  female  26.0      0      0  STON/O2. 3101282   7.9250
3  female  35.0      1      0            113803  53.1000

In [13]:
df.loc[:3, ['Sex', 'Fare', 'Embarked']] #Filas con indices en el rango de [0:3] y columnas con nombre sex, fare y Embarked

Sex     Fare Embarked
0    male   7.2500        S
1  female  71.2833        C
2  female   7.9250        S
3  female  53.1000        S

Tipos de datos en las columnas

In [14]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

La media, Desviacion tipica, Valores minimos y maximos y cuartiles

In [15]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [16]:
df.describe(include='all')

PassengerId    Survived      Pclass            Name   Sex         Age  \
count    891.000000  891.000000  891.000000             891   891  714.000000   
unique          NaN         NaN         NaN             891     2         NaN   
top             NaN         NaN         NaN  Saad, Mr. Amin  male         NaN   
freq            NaN         NaN         NaN               1   577         NaN   
mean     446.000000    0.383838    2.308642             NaN   NaN   29.699118   
std      257.353842    0.486592    0.836071             NaN   NaN   14.526497   
min        1.000000    0.000000    1.000000             NaN   NaN    0.420000   
25%      223.500000    0.000000    2.000000             NaN   NaN   20.125000   
50%      446.000000    0.000000    3.000000             NaN   NaN   28.000000   
75%      668.500000    1.000000    3.000000             NaN   NaN   38.000000   
max      891.000000    1.000000    3.000000             NaN   NaN   80.000000   

             SibSp       Parch Ticket        Fare        Cabin Embarked  
count   891.000000  891.000000    891  891.000000          204      889  
unique         NaN         NaN    681         NaN          147        3  
top            NaN         NaN   1601         NaN  C23 C25 C27        S  
freq           NaN         NaN      7         NaN            4      644  
mean      0.523008    0.381594    NaN   32.204208          NaN      NaN  
std       1.102743    0.806057    NaN   49.693429          NaN      NaN  
min       0.000000    0.000000    NaN    0.000000          NaN      NaN  
25%       0.000000    0.000000    NaN    7.910400          NaN      NaN  
50%       0.000000    0.000000    NaN   14.454200          NaN      NaN  
75%       1.000000    0.000000    NaN   31.000000          NaN      NaN  
max       8.000000    6.000000    NaN  512.329200          NaN      NaN

<h3>Transformar DataFrames</h3>

Eliminar Columnas que no son relevantes

In [3]:
df = df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'])

Eliminar valores vacios

In [4]:
df = df.dropna()

Convertir los Valores Hombre y Mujer en 0 y 1<br>
Convertir la columna Embarked ('C', 'Q' y 'S') en 0, 1 y 2

In [5]:
df['Sex'] = df['Sex'].astype('category').cat.codes

In [6]:
df['Embarked'] = df['Embarked'].astype('category').cat.codes

Añadir una nueva Columna

In [7]:
df['Sex_num'] = df['Sex'].astype('category').cat.codes

<h3>Salvar Ficheros</h3>

Guardar en CSV

In [22]:
df.to_csv('Save/Titanic/titanic_ml.csv', index=False)

Guardar en Excel XLS o XLSX

In [23]:
df.to_excel('Save/Titanic/titanic_ml.xls', index=False)
df.to_excel('Save/Titanic/titanic_ml.xlsx', index=False)

Añadir rutas a un fichero existente

In [24]:
writer = pd.ExcelWriter('Save/Titanic/titanic_2.xlsx')
df.to_excel(writer, sheet_name='Hoja1', index=False)
df.to_excel(writer, sheet_name='Hoja2', index=False)
writer.close() #Se cierre convenientemente

<h3>Preprocesado</h3>

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
def split_label(df, test_size, label):
    train, test= train_test_split(df, test_size=test_size)
    features = df.columns.drop(label)
    train_x = train[features]
    train_y = train[label]
    test_x = test[features]
    test_y = test[label]
    return train_x, train_y, test_x, test_y

In [10]:
train_x, train_y, test_x, test_y = split_label(df, 0.2, 'Survived')

In [11]:
index_embarked = train_x.columns.get_loc('Embarked')

In [12]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler

In [13]:
ohe = OneHotEncoder(
    categorical_features=[index_embarked],
    sparse=False)

In [14]:
train_x_1 = ohe.fit_transform(train_x)

C:\Users\mramirez\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\mramirez\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [15]:
min_max_scaler = MinMaxScaler()
train_x_2 = min_max_scaler.fit_transform(train_x_1)

In [16]:
for i in range(3):
    print(train_x_2[i])

[1.         0.         0.         1.         0.         0.18063784
 0.2        0.         0.02821272 0.        ]
[1.         0.         0.         0.         1.         0.72267742
 0.         0.         0.05797054 1.        ]
[0.         0.         1.         1.         1.         0.44535485
 0.2        0.         0.03035158 1.        ]


<h3>Clasificacion</h3>

Usando SVM (Supervised Virtual Machine) la clase SVC

In [17]:
from sklearn.svm import SVC

In [18]:
clf = SVC()

In [19]:
clf.fit(train_x_2, train_y)

C:\Users\mramirez\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [20]:
test_x_2 = min_max_scaler.transform(ohe.transform(test_x))

In [21]:
clf.predict(test_x_2)

array([1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1], dtype=int64)

In [22]:
clf.score(test_x_2, test_y)

0.8041958041958042

Tiene una tasa de acierto del 80%<br>
k vecinos mas cercanos:

In [23]:
from sklearn.neighbors import KNeighborsClassifier

In [24]:
clf = KNeighborsClassifier()

In [25]:
clf.fit(train_x_2, train_y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [26]:
clf.score(test_x_2, test_y)

0.8251748251748252

<h3>Regresion</h3>

Predecir la tarifa pagada

In [27]:
train_x, train_y, test_x, test_y = split_label(df, 0.2, 'Fare')

In [28]:
index_Embarked = train_x.columns.get_loc('Embarked')

In [29]:
ohe = OneHotEncoder(
    categorical_features=[index_Embarked],
    sparse=False)

In [30]:
train_x_1 = ohe.fit_transform(train_x)

C:\Users\mramirez\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\mramirez\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [31]:
min_max_scaler = MinMaxScaler()
train_x_2 = min_max_scaler.fit_transform(train_x_1)

In [32]:
test_x_2 = min_max_scaler.transform(ohe.transform(test_x))

Usaremos LinearRegression de la biblioteca sklearn.linear_model

In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
reg = LinearRegression()

In [35]:
reg.fit(train_x_2, train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [36]:
reg.score(test_x_2, test_y)

0.4176981655511944

In [37]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [38]:
pred = reg.predict(test_x_2)

In [39]:
mean_squared_error(test_y, pred)

952.3893892037763

In [40]:
mean_absolute_error(test_y, pred)

21.481524475524477

<h3>Analisis de Grupos</h3>

Usaremos K-Means

In [41]:
index_Embarked = df.columns.get_loc('Embarked')
ohe=OneHotEncoder(
    categorical_features=[index_Embarked],
    sparse=False)

In [42]:
titanic_1 = ohe.fit_transform(df)

C:\Users\mramirez\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\mramirez\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [43]:
min_max_scaler = MinMaxScaler()

In [44]:
titanic_2 = min_max_scaler.fit_transform(titanic_1)

In [45]:
 from sklearn.cluster import KMeans

In [46]:
clu = KMeans(n_clusters=3)
clu.fit(titanic_2)
clu.cluster_centers_

array([[ 1.05471187e-15,  4.16666667e-02,  9.58333333e-01,
         1.79687500e-01,  7.12239583e-01,  1.00000000e+00,
         3.75701927e-01,  9.27083333e-02,  4.34027778e-02,
         4.24449926e-02,  1.00000000e+00],
       [ 1.66533454e-16,  6.06060606e-02,  9.39393939e-01,
         7.07070707e-01,  6.03535354e-01,  5.55111512e-16,
         3.41048078e-01,  1.34343434e-01,  1.29629630e-01,
         7.27802307e-02,  5.55111512e-16],
       [ 1.00000000e+00, -9.02056208e-17,  1.22124533e-15,
         6.07692308e-01,  3.73076923e-01,  5.30769231e-01,
         3.81939799e-01,  8.46153846e-02,  6.92307692e-02,
         1.33306411e-01,  5.30769231e-01]])

In [47]:
clu.labels_

array([0, 2, 1, 1, 0, 0, 0, 1, 2, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 2, 0, 2, 0, 0, 1, 2, 1, 1, 2, 1, 1, 0, 0, 2, 1, 2, 1, 2, 1,
       0, 2, 0, 0, 1, 0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 2, 2, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1,
       2, 0, 0, 0, 2, 1, 0, 2, 1, 0, 2, 0, 0, 2, 0, 1, 1, 0, 2, 1, 0, 0,
       2, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 2, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       2, 2, 0, 1, 0, 0, 2, 0, 1, 0, 2, 1, 2, 0, 1, 0, 0, 2, 1, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 2, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 2, 1, 2, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2,
       1, 1, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 2, 2, 1, 0, 2, 1, 2, 0,
       0, 2, 2, 2, 2, 2, 1, 0, 0, 1, 1, 0, 1, 2, 0, 0, 1, 1, 2, 0, 1, 1,
       2, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1,
       1, 0, 2, 2, 0, 0, 2, 2, 2, 0, 0, 2, 1, 1, 2,

In [48]:
from sklearn.metrics import silhouette_score, calinski_harabaz_score

In [49]:
silhouette_score(titanic_2, clu.labels_)

0.4615548686309761

In [50]:
calinski_harabaz_score(titanic_2, clu.labels_)

434.33532552663144

<h3>Tuberias</h3>

Como contruir una tuberia para clasificar los pasajeros del Titanic usando SVM:<br>
1- One Hot encoding para codificar la columna embarked<br>
2- Escalado de todos los atributos al rango [0,1]<br>
3- Entrenamiento de un objeto SVC<br>

In [51]:
train_x, train_y, test_x, test_y = split_label(df, 0.2, 'Survived')

In [52]:
index_Embarked = train_x.columns.get_loc('Embarked')
ohe = OneHotEncoder(
    categorical_features=[index_Embarked],
    sparse=False)

In [53]:
min_max_scaler = MinMaxScaler()
svm = SVC()

In [54]:
 from sklearn.pipeline import Pipeline

In [55]:
pipe = Pipeline([('ohe', ohe),
                ('sca', min_max_scaler),
                ('clf', svm)])

In [56]:
pipe.fit(train_x, train_y)
pipe.score(test_x, test_y)

C:\Users\mramirez\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\mramirez\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)
C:\Users\mramirez\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gam

0.8111888111888111

In [57]:
pipe.predict(test_x)

array([1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0], dtype=int64)

<h3>Persistencia de Modelos</h3>

In [58]:
clu = KMeans(n_clusters = 3)

In [59]:
clu.fit(titanic_2)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [60]:
from sklearn.externals import joblib

In [61]:
joblib.dump(clu, 'Titanic/kmeans.pkl')

['Titanic/kmeans.pkl']

In [62]:
index_Embarked = train_x.columns.get_loc('Embarked')
ohe = OneHotEncoder(
    categorical_features=[index_Embarked],
    sparse=False)
sca = MinMaxScaler()
clu = KMeans(n_clusters = 3)
pipe = Pipeline([('ohe', ohe),
                ('sca', sca),
                ('clu', clu)])

In [63]:
pipe.fit(df)

C:\Users\mramirez\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\mramirez\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


Pipeline(memory=None,
     steps=[('ohe', OneHotEncoder(categorical_features=[6], categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=False)), ('sca', MinMaxScaler(copy=True, feature_range=(0, 1))), ('clu', KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0))])

In [64]:
joblib.dump(pipe, 'Titanic/kmeans_pipeline.pkl')

['Titanic/kmeans_pipeline.pkl']

In [65]:
loaded_pipe = joblib.load('Titanic/kmeans_pipeline.pkl')

<h3>Optimizacion de hiperparametros</h3>

In [68]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm

In [69]:
svc = svm.SVC()

In [70]:
parameters = {'kernel': ['linear', 'rbf'],
             'C': [1,2]}

In [71]:
clf = GridSearchCV(svc, parameters)

In [72]:
clf.fit(train_x, train_y)

C:\Users\mramirez\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\mramirez\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\mramirez\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\mramirez\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default va

GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'kernel': ['linear', 'rbf'], 'C': [1, 2]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [74]:
print(clf.best_params_)

{'C': 1, 'kernel': 'linear'}


In [75]:
print(clf.best_estimator_)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)


In [76]:
clf.predict(test_x)

array([1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0], dtype=int64)